import { createHash, randomBytes } from 'node:crypto';

const KEY_BYTES = 32;
const KEY_PREFIX = 'llmg_';

/**
 * Generates a new API key. The plaintext is returned once and never stored.
 */
export function generateApiKey(): string {
  return `${KEY_PREFIX}${randomBytes(KEY_BYTES).toString('base64url')}`;
}

/**
 * Hashes an API key for storage and lookup.
 *
 * Uses SHA-256 rather than a password hash. The key is generated by us with 256
 * bits of entropy, so there is no guessable search space for bcrypt's work
 * factor to protect, and this runs on every request.
 */
export function hashApiKey(key: string): string {
  return createHash('sha256').update(key).digest('hex');
}
